### ISSUE TITLE
Use bit.dev for your components

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#68]
Have you thought about using https://bit.dev/ for managing your components? This would make integrating, composing and testing a lot easier. We're using it extensively, and it's a complete game changer for us because it enables us to have our complete product as components, that will be composed to bigger components. With their testing process, you can guarantee, that I get only component updates from you that are not breaking my software.

If you want to know more about it, how we're using it, we could also have a chat about it.

**Comment by blvdmitry** [comment]
To be honest, I haven't worked with Bit in the past, only checked their documentation and website. Seems like they've changed quite a lot since the last time. 

What would be the main value of Bit when using it together with Reshaped, considering that we would like to version the whole library with a single version and we have a Storybook setup? I keep thinking of distribution being the main potential benefit for companies already using Bit since we currently work with .tgz files instead of installing from NPM directly but haven't heard from many people using Bit before

**Comment by mmailaender** [comment]
I think the great point about bit is, that it's also open source. So it gets more and more traction. (They're saying they have currently over 200 000 developers on their platform)

Is it mandatory for you that you have to version it as one big thing? Bit is strongly thinking in independent components, e.g. a button. So every component has its own versioning in Bit. That is really beneficial, if you think about introducing breaking changes and updating single components:

Bit runs tests for every component (So far the same as storybook), but it also knows about where the components will be used. e.g. in another Bit component or directly in code. If the tests of your component passing, it will create in all repositories, that using this component a pull request with the new version (like renovate or dependabot, but more proactive). That triggers the tests on my side, so I would see directly in my repo if the new version of your e.g. Button is still working with my codebase. 

They will also provide the possibility in the future to share components permission based to external user. So I don't need to download after every update from your side again the .tgz file and replace it on my side.  Instead, it's a fully automated process. (Currently a big downside about providing code behind Paywalls, because with NPM it's simply not so easy to achieve that)

E.g. here is the library from material-ui: https://bit.cloud/mui-org/material-ui 

And maybe relevant for you in the future: Bit is not only a UI component library like storybook. You can compose and provide with it complete plug'n play Apps and Backend functions: https://bit.dev/docs/apps/apps-overview

**Comment by blvdmitry** [comment]
From what I see with MUI, I think there is just a new version published for every component every time the library is released. Do you know if in the case of MUI the library is also maintained by the Bit team as well for the marketing purposes or by the MUI team? 

In terms of individual changes in general, it adds a lot of unnecessary complexity to the system, since updating one component might lead to a chain of other component updates. In the end, it's much harder to achieve a consistent state of the product over time. I've heard the same feedback about maintaining design systems in other large companies as well. So to solve this problem we instead have a commitment to a predicted major changes release changes: https://reshaped.so/content/docs/getting-started/release-strategy

I guess from our side, we would be looking for their private permissions update since otherwise, we won't be able to distribute it based on the access? And I'm also concerned about the additional overhead. 

By the way, this makes me think about different approaches to downloading the package since your concern of downloading new versions manually stands. We have an experimental token-based approach for Backlight.dev and we currently store a token only for them but in theory, we can open this feature up in the future for regular consumers as well.

**Comment by mmailaender** [comment]
> From what I see with MUI, I think there is just a new version published for every component every time the library is released. Do you know if in the case of MUI the library is also maintained by the Bit team as well for the marketing purposes or by the MUI team?

Good that you're pointing that out - was not aware of that, but it seems that Bit is managing that.

> In terms of individual changes in general, it adds a lot of unnecessary complexity to the system, since updating one component might lead to a chain of other component updates. In the end, it's much harder to achieve a consistent state of the product over time. I've heard the same feedback about maintaining design systems in other large companies as well. So to solve this problem we instead have a commitment to a predicted major changes release changes: https://reshaped.so/content/docs/getting-started/release-strategy

This is one of the big problems that Bit is solving. Because it covers for you the dependency management. We're using it now for some months, and it solves a big pain and was helping us to develop our software strongly as independent components (As bigger the company and higher the complexity as bigger the benefit).

> I guess from our side, we would be looking for their private permissions update since otherwise, we won't be able to distribute it based on the access?

Probably, yes. But maybe adopting the development approach could already help to elevate your architecture.

> By the way, this makes me think about different approaches to downloading the package since your concern of downloading new versions manually stands. We have an experimental token-based approach for Backlight.dev and we currently store a token only for them but in theory, we can open this feature up in the future for regular consumers as well.

Not sure if I'm fully understanding the benefit of this solution. My main concern here is the manual work from downloading up to updating the components in my source code. That what you describe would automatically download it? Something like a GitHub workflow that commits to a repo?

**Comment by blvdmitry** [comment]
Answering the last part, I mean that the workflow would be somewhat similar to the way we usually work with npm packages:
```
"dependencies": {
  "react": "16.0.0"
}
```

But instead of passing just the version, that will actually point to our domain url for downloading the library version, but you won't have to manually download the archive and install the package every time

**Comment by mmailaender** [comment]
Yes, that would help indeed!

**Comment by blvdmitry** [comment]
I'll close this one for housekeeping purposes since we don't have intention of supporting bit.dev for now. Might reopen later
