### ISSUE TITLE
Small problem with dropdown-menu documentation behaviour.

### ISSUE THREAD

**Issue by NadimHallaq** [reshaped/community#71]
Small problem with dropdown-menu documentation behaviour.  when you click on the "Open", the page scrolls up rather than show the dropdown menu contents. 

Steps to recreate:  
Go to Dropdown-menu page [here](https://reshaped.so/content/docs/components/dropdown-menu), scroll down to try some of the examples, if you press on any of them, the pages scrolls to the top, the dropdown menu opens, but you'll have to scroll down to see it.

I tried it on Chrome and Safari.

**Comment by blvdmitry** [comment]
Thanks for the heads-up, we'll take a look

**Comment by blvdmitry** [comment]
Fixed the issue and I think we'll be able to include it into the existing release and not wait for the next one since we have the luxury of just deploying the same version again. I'm also looking at another similar issue with the dropdown menu transitions being used for the wrong position when the originally passed position wasn't fitting into the viewport.
