### ISSUE TITLE
Documentation suggestion/problem

### ISSUE THREAD

**Issue by NadimHallaq** [reshaped/community#77]
Maybe this is entirely unimportant, but it would be nice if we had the the default styles that a component is using in the docs.

Meaning that besides the props that could be changed like padding or variant, components use styles that could only be seen once I change the theme!

Example: The Card component automatically uses the medium Border Radius value, and there is no prop to change it! nor any documentation in the card page! So If I go and change the medium borderRadius value I don't know what other components are going to change as well! Makes sense??

Anyways! Let me know if there is a way to find out? and make theming easier. 

Thanks in advance!

**Comment by blvdmitry** [comment]
That’s a really good idea we’ve been talking about before as well. Is your main case to understand which components will and can be affected by theming? What we’ve discussed before internally was a theming preview, where you can see how themes affect components we have in the library. There are also two related things that can help: 
- runtime theming support which would allow us to create a theme editor right on the website
- theming section for the docs. Probably the easiest solution we can start with and where we can show tokens used for the component

**Comment by NadimHallaq** [comment]
The runtime theming support sounds like a great idea, I image it would be more like the theme preview you have on the homepage but we(users) would be able to customize it! 

The theme section in the docs is a fast fix, just another tab, so It would be Documentation, Properties and Theme, and that would make it clear of what can be changed via props and via theme! 

Anyways good to know that its something your discussing internally!

**Comment by blvdmitry** [comment]
Great, https://github.com/reshaped/community/issues/74 can be tracked for the discussions around the docs improvements.

Regarding the runtime theming, we'll have to figure out the right way to do it since we don't want to include the theming generation logic in runtime for everyone, even if they don't need it. But if we can make it lightweight with theme fragments (one-of token overrides, https://reshaped.so/content/docs/theming/creating-themes#theme-fragments) - we can get quite a lot of flexibility for cases like this
