### ISSUE TITLE
Buttons Style Bug on Next JS Production Build

### ISSUE THREAD

**Issue by imhimi** [reshaped/community#78]
Actionable class over riding the button CSS.

![image](https://user-images.githubusercontent.com/38598267/201332212-aeafc5fb-82ac-4323-9a0b-7a8db41ad0d8.png)

**Comment by blvdmitry** [comment]
Thanks for the heads-up, this is something that has also been reported over email so we started looking into this last week and I've just pushed a documentation rollback for Next 12 as well as a solution for Next 13 app directory that should start working with the next release:

Next 12:
https://github.com/reshaped/community/tree/master/examples/next-starter

Updated it to use the same approach as in some other frameworks. You can find that there is no more custom `next.config.js` and there are a few changes to the imports. CSS is imported only once for the application with `reshaped/bundle.css` and all components are imported from `reshaped/bundle` path. These imports let us pre-build all css using correct selectors order instead of relying on the Next.js build customization.

Next 13:
https://github.com/reshaped/community/tree/master/examples/next-13-starter

With the release of Next 13, new `app` directory is supported in the project which changes the way pages are bundled. Besides all other changes, global css imports within node_modules got native support, so our default ESM build can work out-of-the-box with it. It still requires a few changes in the library (in the starter, I'm using a beta version), like "use client" code for react server components and separation between module and regular css files, so we plan to ship full support in the next Reshaped release, which will make this example work for everyone.
