### ISSUE TITLE
Checkbox error, not visible if checked

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#91]
If the `checkbox` is `checked` and has `hasError`, the `hasError` is not visible 
![image](https://user-images.githubusercontent.com/87228994/207692900-5ce8f976-4d18-469f-8f71-f66105dbc265.png)

**Comment by blvdmitry** [comment]
Checked what other design system do with this just in case. Do you have any existing use case where current behaviour doesn't work? 

I think based on these examples, the one I like the least is having a primary background with a critical border, but also color the whole field with critical might be too much in some cases. So the reason why we went with the current behaviour was because:
- For multiple checkboxes – it's possible to provide an error text which should still highlight that the error is still in place
- For single checkboxes - the only invalid state I can think of is when it's required and not checked. In that case, error should be already visible fine.

Polaris:
<img width="169" alt="image" src="https://user-images.githubusercontent.com/887379/208310561-6b51c4a7-5940-4951-bf38-6a44847895b2.png">

Chakra:
<img width="120" alt="image" src="https://user-images.githubusercontent.com/887379/208310574-8554f30e-b6cb-4d3a-8017-fa9c1bbb226a.png">

Mantine:
<img width="220" alt="image" src="https://user-images.githubusercontent.com/887379/208310588-297464a5-2e01-4075-abe8-e3ae1950d5de.png">

Atlaskit:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/887379/208310622-7b08a146-3cc8-4071-98ad-d02a2d53750f.png">

Spectrum:
<img width="253" alt="image" src="https://user-images.githubusercontent.com/887379/208310645-c340833d-9e28-43cc-b521-a9da1ec3fc24.png">

**Comment by blvdmitry** [comment]
Closing this for housekeeping for now, feel free to comment here if you got any additional examples to share that might conflict with the current behavior
