### ISSUE TITLE
Fetch data component part of scope?

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#92]
Plasmic has a `data fetcher` component, that feels like dealing with dynamic data pretty easy.

![image](https://user-images.githubusercontent.com/87228994/207802236-62e6be32-9a0a-4db7-9ead-fcc71ce3185e.png)
https://www.youtube.com/watch?v=R_fsMjs2kaM

So I'm not sure if you see this as part of the scope of your UI library. For me, it feels like this could help a lot by implementing one often use case quite easy. 

I haven't debugged yet, how the component works from Plasmic in the background. (Although it's possible to export the Plasmic code to check it)

I could imagine, that they do maybe something like that:
GraphQL
```
<dataComponent query={query}>
  <View repead="dataComponent.object.array">
    <SomeOtherComponents />
  </View>
</dataComponent>
```

HTTP
```
<dataComponent endpoint={endpoint}>
  <View repead="dataComponent.object.array">
    <SomeOtherComponents />
  </View>
</dataComponent>
```

**Comment by blvdmitry** [comment]
I think that's out of our scope. Usually implementing any component like this means that either it doesn't work with many integrations developers could use or you have to provide an integration for it. A few similar examples:
- We provide integration guides with frameworks which each have their own requirements so we try to as flexible as possible in our build approach
- Our Image component might be overlapping with Next.js Image component and while they solve slightly different problems, if you're using Next.js Image – you're by like by yourself when it comes to styling it

I think it works better for Plasmic because they have control over the product stack while we don't make hard decisions about that when it's outside of the UI area
