### ISSUE TITLE
View - Align: Stretch seems not working

### ISSUE THREAD

**Issue by mmailaender** [reshaped/community#97]
![image](https://user-images.githubusercontent.com/87228994/209444488-6324bb39-99fe-440e-acea-fd1f5e720a1a.png)

And one more question:

Is the Property `Columns` from `View.Item` the equivalent to `flex-grow`? Because Columns feels more like, that the Viewport is devided in a raster of 12. And depending on the number that I choose, it locates the space. e.g. 8 of 12 or 3 of 12

flex-grow on the other side is more like a relative ratio between all elements that are in the line. Because this was/is confusing me a bit while using View.

**Comment by blvdmitry** [comment]
You're right about the columns, while grow is more like "take all the space left" since we're not providing number values for it. In theory you can get the 6 + 6 columns scenario with 2 items with grow, but for doing things like 4 + 8 - it's columns. One major reason for this is that with grow, semantically we don't expect items to go multiline, while when you're implementing a grid – you can change the size of the columns responsively and they will be handled correctly by just one property

**Comment by mmailaender** [comment]
I think then it could be helpful to make it more clear, that every row or column is max. 12. And after 12 it goes in the next row/column. That means all elements placed in one row/column need to have a sum of 12. (except wrap=false, then it outgrows the parent Element)

**Comment by blvdmitry** [comment]
Fixed the align="stretch" control and I think it works better now combined the flex properties demo in the props tab. Also checked that columns have a description of how their wrapping works
